
#pragma once

#define RGB_MATRIX_DISABLE_SHARED_KEYCODES

#define TAPPING_TERM 175
#define HOLD_ON_OTHER_KEY_PRESS

#define CAPS_WORD_INVERT_ON_SHIFT

#define UNICODE_KEY_WINC KC_F19
#define UNICODE_SELECTED_MODES UNICODE_MODE_WINCOMPOSE

#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_STATIC_LIGHT
#define RGBLIGHT_DEFAULT_ON true
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_TWINKLE


#define AUDIO_INIT_DELAY

#define COIN_SND      E__NOTE(_A5), HD_NOTE(_E6),
#define ONE_UP_SND    Q__NOTE(_E6), Q__NOTE(_G6), Q__NOTE(_E7),  Q__NOTE(_C7),  Q__NOTE(_D7),  Q__NOTE(_G7),
#define MARIO_SND     Q__NOTE(_E5), H__NOTE(_E5), H__NOTE(_E5),  Q__NOTE(_C5),  H__NOTE(_E5),  W__NOTE(_G5), Q__NOTE(_G4),
#define GAMEOVER_SND  HD_NOTE(_C5), HD_NOTE(_G4), H__NOTE(_E4 ), H__NOTE(_A4 ), H__NOTE(_B4 ), H__NOTE(_A4), H__NOTE(_AF4),  H__NOTE(_BF4), H__NOTE(_AF4), WD_NOTE(_G4),
#define MUSHROOM_SND  S__NOTE(_C5), S__NOTE(_G4), S__NOTE(_C5 ), S__NOTE(_E5 ), S__NOTE(_G5 ), S__NOTE(_C6), S__NOTE(_G5 ),  S__NOTE(_GS4), S__NOTE(_C5), S__NOTE(_DS5), S__NOTE(_GS5), S__NOTE(_DS5), S__NOTE(_GS5), S__NOTE(_C6 ), S__NOTE(_DS6), S__NOTE(_GS6), S__NOTE(_DS6), S__NOTE(_AS4), S__NOTE(_D5 ), S__NOTE(_F5 ), S__NOTE(_AS5), S__NOTE(_D6 ), S__NOTE(_F6), S__NOTE(_AS6), S__NOTE(_F6)
#define ST_SND        W__NOTE(_BF3), Q__NOTE(_EF4), WD_NOTE(_AF4), W__NOTE(_REST), H__NOTE(_G4), Q__NOTE(_EF4), H__NOTE(_C4), W__NOTE(_REST), QD_NOTE(_F4), M__NOTE(_BF4, 128),

#define STARTUP_SONG SONG(ST_SND)
#define GOODBYE_SONG SONG(GAMEOVER_SND)

