#pragma once

#define RGB_MATRIX_DISABLE_SHARED_KEYCODES

#define TAPPING_TERM 175
#define HOLD_ON_OTHER_KEY_PRESS

#define CAPS_WORD_INVERT_ON_SHIFT

#define UNICODE_KEY_WINC KC_F19
#define UNICODE_TYPE_DELAY 2
#define UNICODE_SELECTED_MODES UNICODE_MODE_WINCOMPOSE

#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_STATIC_LIGHT
#define RGBLIGHT_DEFAULT_ON true
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_TWINKLE


